### ISSUE TITLE
Can't build fauxdacious

### ISSUE THREAD

**Issue by serrebi** [wildstar84/fauxdacious#9]
On Ubuntu 22.10, can't get dependancies installed.
Here is my output 
sudo apt-get install git automake build-essential libasound2-dev libavformat-dev libbinio-dev libbs2b-dev libcddb2-dev libcdio-cdda-dev libcue-dev libcurl4-gnutls-dev libdbus-glib-1-dev libfaad-dev libflac-dev libfluidsynth-dev libgl1-mesa-dev-lts-utopic libgtk2.0-dev libguess-dev libjack-jackd2-dev liblircclient-dev libmms-dev libmodplug-dev libmp3lame-dev libmpg123-dev libneon27-gnutls-dev libnotify-dev libpulse-dev libsamplerate0-dev libsdl2-dev libsidplayfp-dev libsndfile1-dev libsoxr-dev libvorbis-dev libwavpack-dev libxml2-dev libswscale-dev                            
Reading package lists... Done                                                                                           
Building dependency tree... Done                                                                                        
Reading state information... Done                                                                                       
E: Unable to locate package libgl1-mesa-dev-lts-utopic

**Comment by serrebi** [comment]
Just want to add that I have build-dep audacious just fine on it, just that one package. It looks from a bit of research that it is a dead project of a dependency.

**Comment by wildstar84** [comment]
Looks like that one's no longer needed & I don't even have that one installed!  Can't be sure how it got on this list, but I suspect it may have been required in the past (I put this list together a good while back, and it's been years since I had to set up a fresh development environment).  I've just updated the README file to remove it from the list.  Anyway, try again without it & report back if anything else is missing or isn't available!

Thank you for reporting!

Jim

**Comment by serrebi** [comment]
Ok I'm still getting some errors, here's the output of
sudo apt-get -f install git automake build-essential libasound2-dev \
libavformat-dev libbinio-dev libbs2b-dev libcddb2-dev libcdio-cdda-dev \
libcue-dev libcurl4-gnutls-dev libdbus-glib-1-dev libfaad-dev libflac-dev \
libfluidsynth-dev libgtk2.0-dev libguess-dev \
libjack-jackd2-dev liblircclient-dev libmms-dev libmodplug-dev libmp3lame-dev \
libmpg123-dev libneon27-gnutls-dev libnotify-dev libpulse-dev \
libsamplerate0-dev libsdl2-dev libsidplayfp-dev libsndfile1-dev libsoxr-dev \
libvorbis-dev libwavpack-dev libxml2-dev libswscale-dev
Building dependency tree... 50%

Building dependency tree... Done


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

automake is already the newest version (1:1.16.5-1.3).
automake set to manually installed.
build-essential is already the newest version (12.9ubuntu3).
libgtk2.0-dev is already the newest version (2.24.33-2ubuntu2).
git is already the newest version (1:2.37.2-1ubuntu1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 libgles-dev : Depends: libgles2 (= 1.5.0-1) but 1.4.0-1 is to be installed
 libgles1 : Depends: libglvnd0 (= 1.5.0-1) but 1.4.0-1 is to be installed
 libglvnd-dev : Depends: libglvnd0 (= 1.5.0-1) but 1.4.0-1 is to be installed
 libopengl-dev : Depends: libopengl0 (= 1.5.0-1) but 1.4.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by wildstar84** [comment]
Wish I could (build binary pkgs), but will be a steep learing-curve!  What distro are u running?  I'm running one derived from latest Debian testing, and for example, libgles-dev is at v1.4.0-1 along w/the other libgles* modules, so it looks like you might have some SID or other repositories that are somehow out of sync a bit.

**Comment by serrebi** [comment]
So I was able to build with ./autogen.sh sudo ./configure make sudo make install , but it doesn't open.
here is my output to sudo ./configure --prefix=/usr/local [--enable-qt]
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: [--enable-qt]
checking build system type... Invalid configuration `[--enable-qt]': machine `[--enable' not recognized
configure: error: /bin/bash ./build-aux/config.sub [--enable-qt] failed
I'm blind, so it's possible this could be user error. I hope you can address this though.

**Comment by wildstar84** [comment]
Well, first off, you don't need sudo for configure - only for the "make install" step!  I assume you're dealing with fauxdacious build and haven't gotten to the plugin build yet, and you're in /tmp/fauxdacious/ directory (or whereever you downloaded it to).  I'm also assuming you're trying to build with Qt (and have installed the seven additional Qt libraries required for that).  The docs are slightly dated and you no longer actually need the "--enable-qt" flag, but it's still valid.  Anyway, here's that I get:

/tmp/fauxdacious>./configure --prefix=/usr/local --with-buildstamp=Fauxdacious --enable-qt
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
...
Configuration:

  Install path:                           /usr/local

  D-Bus support:                          yes
  GTK+ support:                           yes
  Qt support:                             yes
  SDL2 (Video) support:                   yes
  Valgrind analysis support:              no

Oh, and (thanks to "Issue 10" filed earlier today), you DON'T need libguess-dev, as this (apparently no longer?) exists either, and is not in the Audacious build requirements list.  The only thing I know of that we require that Aud doesn't is libsdl2-dev (SDL-2) for video/dvd play!  I AM working on improving the README documentation (noting your issues as I go, and want to get this as accurate and painless for future users as possible) since I built that a good while back and it's been a long time and a few Linux upgrades since I had to create a full build environment.  Beyoud that, I'm not sure what you may be doing wrong, or what has gone wrong with your build environment.  Hope this helps!

**Comment by wildstar84** [comment]
Closing due to lack of further response, so assumiing you got it working.  If not, please try latest vsn. (4.2-final) and open new ticket with further detail.
